"use client";
import { useState } from 'react';

export default function BiasDashboard() {
  const [formData, setFormData] = useState({ age: 30, education_num: 12, sex: 1, hours_per_week: 40 });
  const [result, setResult] = useState<any>(null);
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      // This connects to your LIVE Render API we built earlier
      const response = await fetch("https://bias-detection-api.onrender.com/predict", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(formData),
      });
      const data = await response.json();
      setResult(data);
    } catch (error) {
      console.error("Error fetching prediction:", error);
      alert("API is sleeping or disconnected. Check Render logs!");
    }
    setLoading(false);
  };

  return (
    <main className="min-h-screen bg-slate-50 flex items-center justify-center p-4">
      <div className="w-full max-w-xl bg-white rounded-2xl shadow-xl border border-slate-100 overflow-hidden">
        {/* Header */}
        <div className="bg-slate-900 p-6 text-white text-center">
          <h1 className="text-2xl font-bold tracking-tight">⚖️ Ethical AI Guardrail</h1>
          <p className="text-slate-400 text-sm mt-1">SaaS Compliance & Bias Detection Engine</p>
        </div>

        <div className="p-8">
          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <label className="text-sm font-semibold text-slate-700">Applicant Age</label>
                <input type="number" value={formData.age} onChange={(e) => setFormData({...formData, age: parseInt(e.target.value)})} 
                  className="w-full border border-slate-200 p-3 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none transition" />
              </div>
              <div className="space-y-2">
                <label className="text-sm font-semibold text-slate-700">Gender Identity</label>
                <select onChange={(e) => setFormData({...formData, sex: parseInt(e.target.value)})} 
                  className="w-full border border-slate-200 p-3 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none transition">
                  <option value={1}>Male</option>
                  <option value={0}>Female</option>
                </select>
              </div>
            </div>

            <div className="space-y-2">
              <label className="text-sm font-semibold text-slate-700">Work Hours Per Week</label>
              <input type="range" min="1" max="100" value={formData.hours_per_week} onChange={(e) => setFormData({...formData, hours_per_week: parseInt(e.target.value)})} 
                className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-blue-600" />
              <div className="text-right text-xs font-mono text-slate-500">{formData.hours_per_week} Hours</div>
            </div>

            <button type="submit" disabled={loading} className="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-4 rounded-xl shadow-lg shadow-blue-200 transition-all active:scale-95 disabled:opacity-50">
              {loading ? "PROCESSING AUDIT..." : "RUN BIAS AUDIT →"}
            </button>
          </form>

          {/* Result Section */}
          {result && (
            <div className={`mt-8 animate-in fade-in slide-in-from-bottom-4 duration-500`}>
              <div className={`p-6 rounded-xl border-2 ${result.decision === 'Approved' ? 'bg-emerald-50 border-emerald-200' : 'bg-rose-50 border-rose-200'}`}>
                <div className="flex justify-between items-center mb-2">
                  <span className="text-xs font-bold uppercase tracking-wider text-slate-500">System Decision</span>
                  <span className={`px-3 py-1 rounded-full text-xs font-bold ${result.decision === 'Approved' ? 'bg-emerald-500 text-white' : 'bg-rose-500 text-white'}`}>
                    {result.decision}
                  </span>
                </div>
                
                <h3 className={`text-lg font-bold ${result.ethical_audit.includes('Bias') ? 'text-rose-700' : 'text-emerald-700'}`}>
                  {result.ethical_audit}
                </h3>
                
                <p className="text-sm text-slate-600 mt-2">
                  This audit was generated by the {result.raw_score === 1 ? 'Positive' : 'Negative'} mitigation algorithm.
                </p>
              </div>
            </div>
          )}
        </div>
      </div>
    </main>
  );
}